---
# This playbook is for setting up elastic stack
# sudo ansible-playbook -i hosts elk_setup.yml

- hosts: elkmaster
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  vars_files:
    - /test-terraform/aws1/ansible-playbook/group_vars/env_variables

  pre_tasks:
    - name: "Get EC2 instance information"
      setup:
        filter: ansible_*


  roles:
     - role: java
     - role: elk-pre
     - role: elasticsearch
     - role: elasticsearch-master
     - role: logstash
     - role: kibana
     - role: nginx
     - role: kibana-proxy

- hosts: elkdata
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  vars_files:
    - /test-terraform/aws1/ansible-playbook/group_vars/env_variables
  
  pre_tasks:
    - name: "Get EC2 instance information"
      setup:
        filter: ansible_*  

  roles:
     - role: java
     - role: elk-pre
     - role: elasticsearch
     - role: elasticsearch-data
     
