---
# This playbook is for setting up nginx webserver
# Install and configure filebeat and metricbeat on nginx webserver
# sudo ansible-playbook -i hosts nginx.yml


- hosts: nginx
  gather_facts: no
  remote_user: ubuntu
  become: yes
  become_user: root
  vars_files:
    - /test-terraform/aws1/ansible-playbook/group_vars/env_variables

  roles:
     - role: elk-pre
     - role: nginx
     - role: nginx-filebeat
     - role: nginx-metricbeat
  
