---
########################################################
# Prepare to setup metricbeat
########################################################

- name: "Install and enable metricbeat module"
  shell: "{{ item }}" 
  with_items:
    - curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.8.8-amd64.deb
    - sudo dpkg -i metricbeat-6.8.8-amd64.deb
    - metricbeat modules enable nginx
  args:
    warn: no

- name: "Copy metricbeat config"
  template:
    src: metricbeatConf.j2
    dest: /etc/metricbeat/metricbeat.yml


- name: "Enable metricbeat.service"
  systemd:
    name: metricbeat.service
    enabled: yes

- name: "start metricbeat.service"
  service:
    name: metricbeat.service
    state: started
