---
########################################################
# Install ElasticSearch
########################################################

- 
  name: "Install elasticsearch from APT repository"
  apt: 
    name: elasticsearch 
    state: present
    update_cache: yes
- 
  name: "Force systemd to reread configs"
  systemd: 
    daemon_reload: yes
- 
  name: "Enable elasticsearch.service"
  systemd: 
    enabled: true
    name: elasticsearch.service

